package tetzlaff.ibr;//Created by alexk on 8/2/2017.

public enum RenderingMode 
{
    WIREFRAME, LAMBERTIAN_SHADED, PHONG_SHADED, SOLID_TEXTURED, LAMBERTIAN_TEXTURED, MATERIAL_SHADED, IMAGE_BASED_RENDERING, NONE
}
