#!/usr/bin/env bash

#
# Copyright (c) 2019 - 2026 Seth Berrier, Michael Tetzlaff, Jacob Buelow, Luke Denney, Ian Anderson, Zoe Cuthrell, Blane Suess, Isaac Tesch, Nathaniel Willius, Atlas Collins, Simon Cao, Joe Luther, Jakob Schmucki, Nathan Sunday
# Copyright (c) 2019 The Regents of the University of Minnesota
#
# Licensed under GPLv3
# ( http://www.gnu.org/licenses/gpl-3.0.html )
#
# This code is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# This code is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#

# Test historical revisions of Kintsugi 3D Builder.
# Generated by ChatGPT
#
# Usage:
#   ./test-revisions.sh PROJECT_FILE SECONDS RUNS REVISION_LIMIT
#
# Example:
#   ./test-revisions.sh ~/test-project.k3d 30 10 100

set -u

PROJECT_FILE="$1"
WAIT_SECONDS="$2"
RUNS="$3"
REVISION_LIMIT="$4"

MAVEN="/home/deck/Apps/idea/plugins/maven/lib/maven3/bin/mvn"

JAVA_HOME="/home/deck/.jdks/temurin-11.0.27"
export JAVA_HOME

if [[ $# -ne 4 ]]; then
    echo "Usage: $0 PROJECT_FILE SECONDS RUNS REVISION_LIMIT" >&2
    exit 1
fi

BRANCH="disable-materials"
MAIN_CLASS="kintsugi3d.app.Kintsugi3DBuilder"

LOG_DIR="revision-test-logs"
mkdir -p "$LOG_DIR"

SUMMARY_FILE="$LOG_DIR/summary.txt"

if [[ ! -f "$PROJECT_FILE" ]]; then
    echo "Project file does not exist: $PROJECT_FILE" >&2
    exit 1
fi

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "Not inside a git repository." >&2
    exit 1
fi

if ! git show-ref --verify --quiet "refs/heads/$BRANCH"; then
    echo "Branch '$BRANCH' does not exist." >&2
    exit 1
fi

# ----------------------------------------------------------------------
# Save original repository state.
# ----------------------------------------------------------------------

ORIGINAL_REVISION=$(git rev-parse HEAD)
ORIGINAL_BRANCH=$(git symbolic-ref --quiet --short HEAD || true)

cleanup() {
    echo
    echo "Restoring repository to $ORIGINAL_REVISION..."

    git reset --hard "$ORIGINAL_REVISION" >/dev/null 2>&1 || true

    if [[ -n "$ORIGINAL_BRANCH" ]]; then
        git checkout "$ORIGINAL_BRANCH" >/dev/null 2>&1 || true
    fi

    chmod +x test-revisions.sh
}

trap cleanup EXIT INT TERM

# ----------------------------------------------------------------------
# Build the Java classpath.
# ----------------------------------------------------------------------

build_classpath() {
    "$MAVEN" -q dependency:build-classpath \
        -Dmdep.outputFile="$LOG_DIR/classpath.txt"

    if [[ ! -f "$LOG_DIR/classpath.txt" ]]; then
        echo "Could not create Maven dependency classpath." >&2
        return 1
    fi

    CLASSPATH="target/classes:$(cat "$LOG_DIR/classpath.txt")"
}

# ----------------------------------------------------------------------
# Get revisions, newest first.
# ----------------------------------------------------------------------

mapfile -t REVISIONS < <(git rev-list "$BRANCH")

TOTAL_REVISIONS=${#REVISIONS[@]}

if (( REVISION_LIMIT < TOTAL_REVISIONS )); then
    TOTAL_REVISIONS=$REVISION_LIMIT
fi

# ----------------------------------------------------------------------
# Per-revision counters.
# ----------------------------------------------------------------------

declare -A STILL_RUNNING
declare -A JAVA_EXCEPTION
declare -A SYSTEM_CRASH
declare -A NORMAL_EXIT
declare -A COMPILE_FAILURE
declare -A ERROR_MESSAGE

: > "$SUMMARY_FILE"

echo "Kintsugi historical revision test"
echo "================================="
echo "Project:       $PROJECT_FILE"
echo "Wait time:     $WAIT_SECONDS seconds"
echo "Runs/revision: $RUNS"
echo "Revisions:     $TOTAL_REVISIONS"
echo

# ----------------------------------------------------------------------
# Test revisions.
# ----------------------------------------------------------------------

for ((i=0; i<TOTAL_REVISIONS; i++)); do

    REVISION="${REVISIONS[$i]}"
    SHORT_REVISION="${REVISION:0:8}"

    echo
    echo "============================================================"
    echo "Revision $((i+1))/$TOTAL_REVISIONS: $SHORT_REVISION"
    echo "============================================================"

    if ! git checkout --quiet --force "$REVISION"; then
        echo "ERROR: Could not check out revision $REVISION"
        continue
    fi

    # --------------------------------------------------------------
    # Compile.
    # --------------------------------------------------------------

    COMPILE_LOG="$LOG_DIR/${SHORT_REVISION}-compile.log"

    echo "Compiling..."

    if ! "$MAVEN" -q clean compile >"$COMPILE_LOG" 2>&1; then
        echo "COMPILE FAILURE"
        COMPILE_FAILURE["$REVISION"]=1
        continue
    fi

    echo "Compile succeeded."

    # Build classpath for this revision.
    if ! build_classpath >>"$COMPILE_LOG" 2>&1; then
        echo "Could not construct Java classpath."
        COMPILE_FAILURE["$REVISION"]=1
        continue
    fi

    STILL_RUNNING["$REVISION"]=0
    JAVA_EXCEPTION["$REVISION"]=0
    SYSTEM_CRASH["$REVISION"]=0
    NORMAL_EXIT["$REVISION"]=0
    ERROR_MESSAGE["$REVISION"]=0

    # --------------------------------------------------------------
    # Run application repeatedly.
    # --------------------------------------------------------------

    for ((run=1; run<=RUNS; run++)); do

        RUN_LOG="$LOG_DIR/${SHORT_REVISION}-run-${run}.log"

        echo
        echo "Run $run/$RUNS..."

        # Record existing JVM fatal-error logs so that we can identify
        # a new one created by this run.
        BEFORE_HSERR=$(
            find . -maxdepth 1 -name 'hs_err_pid*.log' \
                -printf '%f\n' 2>/dev/null | sort
        )

        "$JAVA_HOME/bin/java" -cp "$CLASSPATH" \
            "$MAIN_CLASS" "$PROJECT_FILE" \
            #> >(tee "$RUN_LOG") 2>&1 &
            >"$RUN_LOG" 2>&1 &

        PID=$!

        # ----------------------------------------------------------
        # Wait for the requested amount of time.
        # ----------------------------------------------------------

        END_TIME=$((SECONDS + WAIT_SECONDS))

        while (( SECONDS < END_TIME )); do

            if ! kill -0 "$PID" 2>/dev/null; then
                break
            fi

            sleep 0.2
        done

        # ----------------------------------------------------------
        # Still alive at timeout.
        # ----------------------------------------------------------

        if kill -0 "$PID" 2>/dev/null; then

            echo "  still running after ${WAIT_SECONDS}s"

            STILL_RUNNING["$REVISION"]=$(( STILL_RUNNING["$REVISION"] + 1 ))

            # Stop it before starting the next test.
            kill "$PID" 2>/dev/null || true

            # Give it a short opportunity to shut down.
            for ((j=0; j<20; j++)); do
                if ! kill -0 "$PID" 2>/dev/null; then
                    break
                fi
                sleep 0.1
            done

            # Don't let a stuck application prevent the next test.
            kill -9 "$PID" 2>/dev/null || true

            wait "$PID" 2>/dev/null || true

            if grep -q 'ERROR' "$RUN_LOG"; then
                echo "  ERROR message detected in Kintsugi output."
                ERROR_MESSAGE["$REVISION"]=$(( ERROR_MESSAGE["$REVISION"] + 1 ))
            fi

            continue
        fi

        # ----------------------------------------------------------
        # Process terminated before timeout.
        # ----------------------------------------------------------

        wait "$PID"
        EXIT_CODE=$?

        # Look for a newly created JVM fatal-error log.
        AFTER_HSERR=$(
            find . -maxdepth 1 -name 'hs_err_pid*.log' \
                -printf '%f\n' 2>/dev/null | sort
        )

        NEW_HSERR=""

        while read -r H; do
            [[ -z "$H" ]] && continue

            if ! grep -qxF "$H" <<< "$BEFORE_HSERR"; then
                NEW_HSERR="$H"
                break
            fi
        done <<< "$AFTER_HSERR"

        echo "  terminated early (exit code $EXIT_CODE)"

        if [[ -n "$NEW_HSERR" ]]; then
            echo "  fatal JVM error log: $NEW_HSERR"
        fi

        # ----------------------------------------------------------
        # Classify termination.
        #
        # A newly generated hs_err_pid file takes precedence because
        # it indicates a fatal JVM/native failure.
        #
        # Unix processes terminated by a signal normally return
        # 128 + signal number:
        #
        #   132 = SIGILL
        #   134 = SIGABRT
        #   135 = SIGBUS
        #   136 = SIGFPE
        #   139 = SIGSEGV
        #
        # Exit code 0 = normal early termination.
        #
        # Other nonzero exit codes are treated as Java/application
        # failures.
        # ----------------------------------------------------------

        if [[ -n "$NEW_HSERR" ]]; then

            echo "  -> native/JVM fatal error"

            SYSTEM_CRASH["$REVISION"]=$(
                ((${SYSTEM_CRASH[$REVISION]} + 1))
            )

        else

            case "$EXIT_CODE" in

                132|134|135|136|139)
                    echo "  -> native/system crash"

                    SYSTEM_CRASH["$REVISION"]=$(( SYSTEM_CRASH["$REVISION"] + 1 ))
                    ;;

                0)
                    echo "  -> normal early termination"

                    NORMAL_EXIT["$REVISION"]=$(( NORMAL_EXIT["$REVISION"] + 1 ))
                    ;;

                *)
                    echo "  -> Java/application exception"

                    JAVA_EXCEPTION["$REVISION"]=$(( JAVA_EXCEPTION["$REVISION"] + 1 ))
                    ;;

            esac

        fi

    done

    # --------------------------------------------------------------
    # Revision summary.
    # --------------------------------------------------------------

    SUMMARY_LINE="$SHORT_REVISION: still running ${STILL_RUNNING[$REVISION]}, error log ${ERROR_MESSAGE[$REVISION]}, exception ${JAVA_EXCEPTION[$REVISION]}, system crash ${SYSTEM_CRASH[$REVISION]}, normal exit ${NORMAL_EXIT[$REVISION]}"

    echo
    echo "$SUMMARY_LINE"
    echo "$SUMMARY_LINE" >> "$SUMMARY_FILE"

done

# ----------------------------------------------------------------------
# Final summary table.
# ----------------------------------------------------------------------

echo
echo
echo "============================================================"
echo "FINAL SUMMARY"
echo "============================================================"

printf "%-12s %12s %12s %12s %12s %12s %12s\n" \
    "Revision" \
    "Running" \
    "Error log" \
    "Exception" \
    "Sys. Crash" \
    "Normal Exit" \
    "Compile Fail"

printf "%-12s %12s %12s %12s %12s %12s %12s\n" \
    "--------" \
    "-------" \
    "-----" \
    "---------" \
    "---------" \
    "-----------" \
    "------------"

for ((i=0; i<TOTAL_REVISIONS; i++)); do

    REVISION="${REVISIONS[$i]}"
    SHORT_REVISION="${REVISION:0:8}"

    if [[ -n "${COMPILE_FAILURE[$REVISION]+x}" ]]; then

        printf "%-12s %12s %12s %12s %12s %12s %12s\n" \
            "$SHORT_REVISION" \
            "-" \
            "-" \
            "-" \
            "-" \
            "-" \
            "YES"

    else

        printf "%-12s %12d %12d %12d %12d %12d %12d\n" \
            "$SHORT_REVISION" \
            "${STILL_RUNNING[$REVISION]}" \
            "${ERROR_MESSAGE[$REVISION]}" \
            "${JAVA_EXCEPTION[$REVISION]}" \
            "${SYSTEM_CRASH[$REVISION]}" \
            "${NORMAL_EXIT[$REVISION]}" \
            "0"
    fi

done

echo
echo "Detailed logs: $LOG_DIR/"
echo "Summary:       $SUMMARY_FILE"
