package tetzlaff.ibrelight.tools;

public enum KeyPressToolType
{
    ENVIRONMENT_BRIGHTNESS_UP_LARGE,
    ENVIRONMENT_BRIGHTNESS_DOWN_LARGE,
    ENVIRONMENT_BRIGHTNESS_UP_SMALL,
    ENVIRONMENT_BRIGHTNESS_DOWN_SMALL,
    TOGGLE_LIGHTS,
    TOGGLE_LIGHT_WIDGETS,
}
