#ifndef OVERLAY_MODES
#define OVERLAY_MODES

#line 5 3104

#define OVERLAY_MODE_NONE 0
#define OVERLAY_MODE_WEIGHTMAP 1

#ifndef OVERLAY_MODE
#define OVERLAY_MODE OVERLAY_MODE_NONE
#endif

#if OVERLAY_MODE == OVERLAY_MODE_WEIGHTMAP

#ifndef OVERLAY_WEIGHTMAP_INDEX
#define OVERLAY_WEIGHTMAP_INDEX 0
#endif

#endif // OVERLAY_MODE == OVERLAY_MODE_WEIGHTMAP

#endif // OVERLAY_MODES
