package tetzlaff.gl;

public enum PrimitiveMode 
{
	POINTS, 
	LINE_STRIP, 
	LINE_LOOP, 
	LINES, 
	LINE_STRIP_ADJACENCY, 
	LINES_ADJACENCY, 
	TRIANGLE_STRIP, 
	TRIANGLE_FAN, 
	TRIANGLES, 
	TRIANGLE_STRIP_ADJACENCY, 
	TRIANGLES_ADJACENCY, 
	PATCHES
}
