package tetzlaff.gl.core;

public enum SamplerType
{
    FLOAT_1D,
    FLOAT_2D,
    FLOAT_3D,
    FLOAT_CUBE_MAP,
    FLOAT_1D_ARRAY,
    FLOAT_2D_ARRAY,

    INTEGER_1D,
    INTEGER_2D,
    INTEGER_3D,
    INTEGER_CUBE_MAP,
    INTEGER_1D_ARRAY,
    INTEGER_2D_ARRAY,

    UNSIGNED_INTEGER_1D,
    UNSIGNED_INTEGER_2D,
    UNSIGNED_INTEGER_3D,
    UNSIGNED_INTEGER_CUBE_MAP,
    UNSIGNED_INTEGER_1D_ARRAY,
    UNSIGNED_INTEGER_2D_ARRAY
}
