name: Build

on:
  push:
    branches: [ 'main', 'build-automation' ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ 'main' ]

env:
  java-version: 11

jobs:
  build:
    name: Build ${{ matrix.os }} distributions
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact: '*setup.exe'
            
          - os: macos-latest
            artifact: '*macos.dmg'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: '${{ env.java-version }}'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Maven build and test
        run: mvn --batch-mode --update-snapshots verify

      - name: Store build directory
        id: build-dir
        run: |
          BUILD_DIR=$(mvn help:evaluate -Dexpression=project.build.directory -q -DforceStdout)
          echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ${{ steps.build-dir.outputs.BUILD_DIR }}/${{ matrix.artifact }}
