name: Build

on:
  push:
    branches: [ 'main', 'build-automation' ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ 'main' ]

env:
  java-version: 11

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: '${{ env.java-version }}'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Maven build and test
        run: mvn --batch-mode --update-snapshots verify
